/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/rob/catkin_ws/src/dlut_motor_hokuyo/msg/motor.msg
 *
 */


#ifndef DLUT_MOTOR_HOKUYO_MESSAGE_MOTOR_H
#define DLUT_MOTOR_HOKUYO_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dlut_motor_hokuyo/UInt32.h>
#include <dlut_motor_hokuyo/UInt32.h>

namespace dlut_motor_hokuyo
{
template <class ContainerAllocator>
struct motor_
{
  typedef motor_<ContainerAllocator> Type;

  motor_()
    : motor_freq()
    , num_of_pulse_per_circle()  {
    }
  motor_(const ContainerAllocator& _alloc)
    : motor_freq(_alloc)
    , num_of_pulse_per_circle(_alloc)  {
    }



   typedef  ::dlut_motor_hokuyo::UInt32_<ContainerAllocator>  _motor_freq_type;
  _motor_freq_type motor_freq;

   typedef  ::dlut_motor_hokuyo::UInt32_<ContainerAllocator>  _num_of_pulse_per_circle_type;
  _num_of_pulse_per_circle_type num_of_pulse_per_circle;




  typedef boost::shared_ptr< ::dlut_motor_hokuyo::motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dlut_motor_hokuyo::motor_<ContainerAllocator> const> ConstPtr;

}; // struct motor_

typedef ::dlut_motor_hokuyo::motor_<std::allocator<void> > motor;

typedef boost::shared_ptr< ::dlut_motor_hokuyo::motor > motorPtr;
typedef boost::shared_ptr< ::dlut_motor_hokuyo::motor const> motorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dlut_motor_hokuyo::motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dlut_motor_hokuyo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'dlut_motor_hokuyo': ['/home/rob/catkin_ws/src/dlut_motor_hokuyo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dlut_motor_hokuyo::motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dlut_motor_hokuyo::motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dlut_motor_hokuyo::motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "151060cee652980d6292a2bc72f122c9";
  }

  static const char* value(const ::dlut_motor_hokuyo::motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x151060cee652980dULL;
  static const uint64_t static_value2 = 0x6292a2bc72f122c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dlut_motor_hokuyo/motor";
  }

  static const char* value(const ::dlut_motor_hokuyo::motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "UInt32 motor_freq         #the frequency we send the pulse to the motor\n\
UInt32 num_of_pulse_per_circle	#the number of the pulse a circle of sick\n\
\n\
================================================================================\n\
MSG: dlut_motor_hokuyo/UInt32\n\
uint32 data\n\
";
  }

  static const char* value(const ::dlut_motor_hokuyo::motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_freq);
      stream.next(m.num_of_pulse_per_circle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dlut_motor_hokuyo::motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dlut_motor_hokuyo::motor_<ContainerAllocator>& v)
  {
    s << indent << "motor_freq: ";
    s << std::endl;
    Printer< ::dlut_motor_hokuyo::UInt32_<ContainerAllocator> >::stream(s, indent + "  ", v.motor_freq);
    s << indent << "num_of_pulse_per_circle: ";
    s << std::endl;
    Printer< ::dlut_motor_hokuyo::UInt32_<ContainerAllocator> >::stream(s, indent + "  ", v.num_of_pulse_per_circle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DLUT_MOTOR_HOKUYO_MESSAGE_MOTOR_H
